AllCops:
  TargetRubyVersion: 2.7
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/config.ru'
    - '**/*.rake'
  Exclude:
    - vendor/**/*
    - db/migrations/**/*

  DisplayCopNames:
    Enabled: true

  DisplayStyleGuide:
    Enabled: true

Naming/FileName:
  Exclude:
  - Guardfile
  - Vagrantfile
  - test/Vagrantfile
  - Dockerfile

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Layout/LineLength:
  Max: 180
  Exclude:
    - spec/**/*

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
